runtime: nodejs18

env: standard

service: default
handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html
# ... other configuration options (optional)

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "./justcall-378101-79e45cb3c455.json"
