//Routes
const authRoutes = require("./routes/auth");
const usersRoutes = require("./routes/users");
const chatRoutes = require("./routes/chat");
const contactRoutes = require("./routes/contacts");
const emailRoutes = require("./routes/email");
const boardRoutes = require("./routes/boards");
const boardTeamRoutes = require("./routes/board_team");
const tasksRoutes = require("./routes/tasks");
const taskBoardRoutes = require("./routes/task-boards");
const callRoutes = require("./routes/call");
const todoRoutes = require("./routes/todo");
const galleryRoutes = require("./routes/gallery");
const postRoutes = require("./routes/post");
const calendarEventRoutes = require("./routes/calendar_events");
const invoiceRoutes = require("./routes/invoice");
const twilioRoutes = require("./routes/twilio");
const agentsRoutes = require("./routes/agents");
const paymentRoutes = require("./routes/payments");
const cardRoutes = require("./routes/cards");
const subscriptionRoutes = require("./routes/subscriptions");
const dashboardRoutes = require("./routes/dashboard");
const billingRoutes = require("./routes/billings");
const kycRoutes = require("./routes/kyc");
const ticketRoutes = require("./routes/tickets");
const balanceRoutes = require("./routes/balance");
const notificationRoutes = require("./routes/notification");
const ratesRoutes = require("./routes/plan-rates");
const brandRoutes = require("./routes/brands");
const permissionRoutes = require("./routes/permissions");
const a2pverification = require("./routes/a2pVerification");

app.use("/v1/auth", authRoutes);
app.use("/v1/user", usersRoutes);
app.use("/v1/user/chat", chatRoutes);
app.use("/v1/user/contact", contactRoutes);
app.use("/v1/user/email", emailRoutes);
app.use("/v1/user/board", boardRoutes);
app.use("/v1/user/board/team", boardTeamRoutes);
app.use("/v1/user/board/task", tasksRoutes);
app.use("/v1/user/board/task/board", taskBoardRoutes);
app.use("/v1/user/call", callRoutes);
app.use("/v1/user/todos", todoRoutes);
app.use("/v1/user/gallery", galleryRoutes);
app.use("/v1/user/post", postRoutes);
app.use("/v1/user/calendar", calendarEventRoutes);
app.use("/v1/user/invoice", invoiceRoutes);
app.use("/v1/user/calling", twilioRoutes);
app.use("/v1/user/agents", agentsRoutes);
app.use("/v1/user/payments", paymentRoutes);
app.use("/v1/user/cards", cardRoutes);
app.use("/v1/user/subscriptions", subscriptionRoutes);
app.use("/v1/user/dashboard", dashboardRoutes);
app.use("/v1/user/billing", billingRoutes);
app.use("/v1/user/kyc", kycRoutes);
app.use("/v1/user/ticket", ticketRoutes);
app.use("/v1/user/balance", balanceRoutes);
app.use("/v1/user/notifications", notificationRoutes);
app.use("/v1/user/rates", ratesRoutes);
app.use("/v1/user/brand", brandRoutes);
app.use("/v1/user/permissions", permissionRoutes);
app.use("/v1/user/verifications", a2pverification);
